name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up build variables
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/setup_build_variables.sh

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'linux'
        install-deps: 'true'

    - name: Install dependencies
      run: sudo apt-get install extra-cmake-modules libxcb-xfixes0-dev xvfb

    - name: Set up kColorPicker
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/setup_kColorPicker.sh "Unix Makefiles"
        
    - name: Set up kImageAnnotator
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/setup_kImageAnnotator.sh "Unix Makefiles"
        
    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        mkdir build && cd build
        cmake .. -DBUILD_TESTS=ON -DVERSION_SUFIX=${{ env.VERSION_SUFFIX }} -DBUILD_NUMBER=${{ env.BUILD_NUMBER }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_PREFIX }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        make

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: xvfb-run --auto-servernum --server-num=1 --server-args="-screen 0 1024x768x24" make test CTEST_OUTPUT_ON_FAILURE=1

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-package
        path: ${{github.workspace}}/build

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          body: "Release body text"
          tag: "continuous"
          prerelease: true
          token: "${{ secrets.GITHUB_TOKEN }}"
          commit: master
          name: "Continuous build"
