name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up build variables
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/setup_build_variables.sh

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'mac'
        install-deps: 'true'
        
    - name: Set up kColorPicker
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/setup_kColorPicker.sh "Unix Makefiles"
        
    - name: Set up kImageAnnotator
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/setup_kImageAnnotator.sh "Unix Makefiles"
        
    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        mkdir build && cd build
        cmake .. -DBUILD_TESTS=ON -DVERSION_SUFIX=${{ env.VERSION_SUFFIX }} -DBUILD_NUMBER=${{ env.BUILD_NUMBER }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_PREFIX }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES=${{ env.INSTALL_PREFIX }}/include/kImageAnnotator
        make

    - name: 'Tar files'
      run: tar -cvf build-package.tar ${{github.workspace}}/build

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-package
        path: ${{github.workspace}}/build-package.tar

  test:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-package
          path: ${{github.workspace}}/build

#      - name: Test
#        working-directory: ${{github.workspace}}/build
#        run: make test CTEST_OUTPUT_ON_FAILURE=1

  release:
    needs: test
    runs-on: macos-latest
    steps:
      - name: Test
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "continuous"
          prerelease: true
          title: "Continuous build"
