name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Define Release Number
      run: |
        VERSION_REGEX="([0-9]{1,}\.)+[0-9]{1,}"
        export BUILD_TIME=$(date +"%a, %d %b %Y %T %z")
        export BUILD_DATE=$(date  +"%a %b %d %Y")
        export BUILD_NUMBER=$(git rev-list --count HEAD)-$(git rev-parse --short HEAD)
        export VERSION_NUMBER=$(grep "project.*" CMakeLists.txt | egrep -o "${VERSION_REGEX}")
        export INSTALL_PREFIX="${{github.workspace}}"
        export BUILD_TYPE="Release"
        
        echo "Build number is $BUILD_NUMBER"
        echo "Version number is $VERSION_NUMBER"
                
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'mac'
        install-deps: 'true'
        
    - name: Setup kColorPicker
      working-directory: ${{github.workspace}}
      run: |
        echo "--> Building ksnip with latest version of kColorPicker"
        git clone --depth 1 git://github.com/ksnip/kColorPicker
        
        echo $PATH
        echo $LDFLAGS
        echo $CPPFLAGS
        
        cd kColorPicker
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBUILD_EXAMPLE=OFF -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}
        make && sudo make install
        
    - name: Setup kImageAnnotator
      working-directory: ${{github.workspace}}
      run: |
        ls -al
        echo "--> Building ksnip with latest version of kImageAnnotator"
        git clone --depth 1 git://github.com/ksnip/kImageAnnotator
        
        cd kImageAnnotator
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBUILD_EXAMPLE=OFF -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}
        make && sudo make install
        
    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        mkdir build && cd build
        cmake .. -DVERSION_SUFIX=${VERSION_SUFFIX} -DBUILD_NUMBER=${BUILD_NUMBER} -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES=/usr/local/include/kImageAnnotator
        make    
