name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up build variables
      run: bash ./.github/scripts/setup_build_variables.sh

    - name: Set up windows build variables
      run: bash ./.github/scripts/macos/setup_macos_build_variables.sh

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'mac'
        install-deps: 'true'
        
    - name: Set up kColorPicker
      run: bash ./.github/scripts/setup_kColorPicker.sh
        
    - name: Set up kImageAnnotator
      run: bash ./.github/scripts/setup_kImageAnnotator.sh
        
    - name: Build
      env:
        BUILD_TESTS: ON
      run: bash ./.github/scripts/build_ksnip.sh

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: make test CTEST_OUTPUT_ON_FAILURE=1


  package-dmg:
    runs-on: macos-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up build variables
        run: bash ./.github/scripts/setup_build_variables.sh

      - name: Set up windows build variables
        run: bash ./.github/scripts/macos/setup_macos_build_variables.sh

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'mac'
          install-deps: 'true'

      - name: Set up kColorPicker
        run: bash ./.github/scripts/setup_kColorPicker.sh

      - name: Set up kImageAnnotator
        run: bash ./.github/scripts/setup_kImageAnnotator.sh

      - name: Build
        run: bash ./.github/scripts/build_ksnip.sh

      - name: Package dmg
        run: bash ./.github/scripts/macos/package_dmg.sh

      - name: Add OSX certificate to key chain
        run: bash ./.github/scripts/macos/add_osx_cert.sh

      - name: Notarize dmg package
        run: bash ./.github/scripts/macos/notarize_osx_dmg_package.sh

      - name: Upload files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
          bash upload.sh ksnip-*.dmg
