name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup build variables
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/setup_build_variables.sh

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
        install-deps: 'true'
        arch: 'win64_mingw81'
        
    - name: Setup kColorPicker
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/setup_kColorPicker.sh "MinGW Makefiles"
        
    - name: Setup kImageAnnotator
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/setup_kImageAnnotator.sh "MinGW Makefiles"
        
    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        setx CPLUS_INCLUDE_PATH "${{ env.INSTALL_PREFIX }}/include/kImageAnnotator" /M
        setx C_INCLUDE_PATH "${{ env.INSTALL_PREFIX }}/include/kImageAnnotator" /M
        echo "LIB=$LIB"
        echo "INCLUDE=$INCLUDE"

        echo "--------------------"
        ls ${{ env.INSTALL_PREFIX }}/include/kImageAnnotator
        echo "--------------------"

        mkdir build && cd build

        ls

        cmake .. -G"MinGW Makefiles" VERBOSE=1 -DVERSION_SUFIX=${{ env.VERSION_SUFFIX }} -DBUILD_NUMBER=${{ env.BUILD_NUMBER }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_PREFIX }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES="${{ env.INSTALL_PREFIX }}/include/kImageAnnotator"
        make
