name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up build variables
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/setup_build_variables.sh

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
        install-deps: 'true'
        arch: 'win64_msvc2017_64'

    - name: Set up nmake
      uses: ilammy/msvc-dev-cmd@v1
        
    - name: Set up kColorPicker
      working-directory: ${{github.workspace}}
      run: |
        echo "--> Install latest version of kColorPicker"
        git clone --depth 1 git://github.com/ksnip/kColorPicker

        cd kColorPicker || exit
        mkdir build && cd build || exit
        cmake .. -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DBUILD_EXAMPLE=OFF -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_PREFIX }} -DCMAKE_CXX_COMPILER=cl
        nmake VERBOSE=1 && make install
        
    - name: Set up kImageAnnotator
      working-directory: ${{github.workspace}}
      run: |
        echo "--> Install latest version of kImageAnnotator"
        git clone --depth 1 git://github.com/ksnip/kImageAnnotator

        cd kImageAnnotator || exit
        mkdir build && cd build || exit
        cmake .. -G"NMake Makefiles" -D -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DBUILD_EXAMPLE=OFF -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_PREFIX }}
        nmake && make install
      env:
        LIB: "${{ env.INSTALL_PREFIX }}/lib"
        INCLUDE: "${{ env.INSTALL_PREFIX }}/include"
        
    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        mkdir build && cd build
        cmake .. -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DVERSION_SUFIX=${{ env.VERSION_SUFFIX }} -DBUILD_NUMBER=${{ env.BUILD_NUMBER }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_PREFIX }}
        nmake VERBOSE=1
      env:
        LIB: "${{ env.INSTALL_PREFIX }}/lib"
        INCLUDE: "${{ env.INSTALL_PREFIX }}/include"
