name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up build variables
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/setup_build_variables.sh

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
        install-deps: 'true'
        arch: 'win64_mingw81'
        
    - name: Set up kColorPicker
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/setup_kColorPicker.sh "MinGW Makefiles"
        
    - name: Set up kImageAnnotator
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/setup_kImageAnnotator.sh "MinGW Makefiles"
        
    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        mkdir build && cd build

        echo "1. CMAKE_LIBRARY_PATH ->  $CMAKE_LIBRARY_PATH"
        echo "1. env.CMAKE_LIBRARY_PATH -> ${{ env.CMAKE_LIBRARY_PATH }}"

        export CMAKE_LIBRARY_PATH="$CMAKE_LIBRARY_PATH:${{ env.INSTALL_PREFIX }}/lib"

        echo "2. CMAKE_LIBRARY_PATH ->  $CMAKE_LIBRARY_PATH"
        echo "2. env.CMAKE_LIBRARY_PATH -> ${{ env.CMAKE_LIBRARY_PATH }}"

        cmake .. -G"MinGW Makefiles" -D CMAKE_CXX_FLAGS="-D_WIN32_WINNT=0x0A00" -DVERSION_SUFIX=${{ env.VERSION_SUFFIX }} -DBUILD_NUMBER=${{ env.BUILD_NUMBER }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_PREFIX }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES="${{ env.INSTALL_PREFIX }}/include"
        make VERBOSE=1
