name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up build variables
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/setup_build_variables.sh

    - name: Set up windows build variables
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/setup_windows_build_variables.sh

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
        install-deps: 'true'
        arch: 'win64_msvc2019_64'

    - name: Set up nmake
      uses: ilammy/msvc-dev-cmd@v1

    - name: Set up kColorPicker
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/setup_kColorPicker.sh
        
    - name: Set up kImageAnnotator
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/setup_kImageAnnotator.sh

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        mkdir build && cd build
        cmake .. -G"${{ env.CMAKE_GENERATOR }}" -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DVERSION_SUFIX=${{ env.VERSION_SUFFIX }} -DBUILD_NUMBER=${{ env.BUILD_NUMBER }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_PREFIX }} -DOPENSSL_DIR="${{ env.OPENSSL_DIR }}" -DKIMAGEANNOTATOR_DIR=${{ env.INSTALL_PREFIX }}
        nmake

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: nmake test CTEST_OUTPUT_ON_FAILURE=1

    - name: Download OpenSSL
      working-directory: ${{github.workspace}}
      run: |
        curl "https://indy.fulgan.com/SSL/openssl-1.0.2q-i386-win32.zip" --output openssl.zip
        7z x openssl.zip -o"${{ env.OPENSSL_DIR }}" || true

    - name: Package exe
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/package_exe.sh

    - name: Package msi
      working-directory: ${{github.workspace}}
      run: sh ./.github/scripts/package_msi.sh

    - name: Upload files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl "https://github.com/probonopd/uploadtool/raw/master/upload.sh"
        bash upload.sh ksnip-*.zip
        bash upload.sh ksnip-*.msi

